export interface Userdata {
    loginid : string | undefined,
    usertype: number,
    name : string,
    surname : string,
    gender : string,
    dob : string,
    parentsname : string,
    contactnumber : string,
    whatsappnumber : string,
    city : string,
    teachername : string,
    additionalinfo : string,
    photourl : string,
    dataverifieddate : string,
    dataverifiedby : string,
    admincomments : string,
    accepted : boolean,
    accountsuspended : boolean,    
}
